"""
Compose MT infographic images into a vertical MP4 for Douyin/video-channel drafts.

Input: ordered image files.
Output: a 1080x1920 H.264 MP4 slideshow generated by ffmpeg.
"""

from __future__ import annotations

import argparse
import subprocess
import tempfile
from pathlib import Path

from ffmpeg_utils import resolve_ffmpeg


IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp"}


def require_ffmpeg() -> str:
    """返回 ffmpeg 路径（PATH 或 imageio-ffmpeg 内置）。"""
    return resolve_ffmpeg()


def quote_concat_path(path: Path) -> str:
    raw = path.resolve().as_posix()
    if "\n" in raw or "\r" in raw:
        raise ValueError(f"Image path contains newlines, which breaks concat format: {raw}")
    return raw.replace("'", "'\\''")


def validate_images(paths: list[str]) -> list[Path]:
    images = [Path(p).resolve() for p in paths]
    missing = [p for p in images if not p.exists()]
    if missing:
        raise SystemExit("[ERROR] missing image: " + str(missing[0]))
    invalid = [p for p in images if p.suffix.lower() not in IMAGE_EXTS]
    if invalid:
        raise SystemExit("[ERROR] unsupported image type: " + str(invalid[0]))
    return images


def build_concat_file(images: list[Path], seconds: float) -> str:
    lines: list[str] = []
    for image in images:
        lines.append(f"file '{quote_concat_path(image)}'")
        lines.append(f"duration {seconds}")
    lines.append(f"file '{quote_concat_path(images[-1])}'")
    return "\n".join(lines) + "\n"


def compose_video(images: list[Path], output: Path, seconds: float, audio: Path | None = None) -> None:
    ffmpeg = require_ffmpeg()
    output.parent.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="kg-douyin-video-") as tmp:
        concat_path = Path(tmp) / "images.txt"
        concat_path.write_text(build_concat_file(images, seconds), encoding="utf-8")

        vf = (
            "scale=1080:1920:force_original_aspect_ratio=decrease,"
            "pad=1080:1920:(ow-iw)/2:(oh-ih)/2:color=#F0EDE6,"
            "setsar=1,format=yuv420p"
        )
        cmd = [
            ffmpeg,
            "-y",
            "-f",
            "concat",
            "-safe",
            "0",
            "-i",
            str(concat_path),
        ]
        if audio:
            if not audio.exists():
                raise SystemExit(f"[ERROR] audio not found: {audio}")
            cmd.extend(["-i", str(audio.resolve())])
        cmd.extend([
            "-vf",
            vf,
            "-r",
            "30",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            "-movflags",
            "+faststart",
        ])
        if audio:
            cmd.extend(["-c:a", "aac", "-shortest"])
        cmd.append(str(output.resolve()))

        try:
            result = subprocess.run(
                cmd, check=True, capture_output=True, text=True,
                encoding="utf-8", errors="replace",
            )
        except subprocess.CalledProcessError as exc:
            if exc.stderr:
                print(f"[ffmpeg stderr] {exc.stderr.strip()}")
            raise SystemExit(exc.returncode) from exc
        if result.stderr:
            print(f"[ffmpeg stderr] {result.stderr.strip()}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Compose KG tutorial images into a Douyin-ready MP4")
    parser.add_argument("--images", nargs="+", required=True, help="Ordered image files")
    parser.add_argument("--output", required=True, help="Output mp4 path")
    parser.add_argument("--seconds", type=float, default=2.8, help="Seconds per image")
    parser.add_argument("--audio", help="Optional background audio file")
    args = parser.parse_args()

    if args.seconds <= 0:
        raise SystemExit("[ERROR] --seconds must be greater than 0")

    images = validate_images(args.images)
    compose_video(images, Path(args.output), args.seconds, Path(args.audio).resolve() if args.audio else None)
    print(f"[OK] video written to: {Path(args.output).resolve()}")


if __name__ == "__main__":
    main()
